- hosts: lpar
  vars:
    rhsm_username: "{{ vault_rhsm_user }}"
    rhsm_password: "{{ vault_rhsm_password }}"
    rhsm_pool_ids: "{{ vault_rhsm_pool_id }}"
    rhsm_repos:
      - rhel-7-for-power-le-rpms
      - rhel-7-for-power-le-extras-rpms
      - rhel-7-for-power-le-optional-rpms
      - rhel-7-server-ansible-2.6-for-power-le-rpms
      - rhel-7-server-for-power-le-rhscl-rpms
      - rhel-7-for-power-le-ose-3.11-rpms   
  roles:
    - openstack.redhat-subscription
