- block:
    - import_tasks: register.yml

  rescue:
    - block:
        - name: Manage Red Hat subscription (force)
          redhat_subscription:
            username: "{{ rhsm_username | default(omit) }}"
            password: "{{ rhsm_password | default(omit) }}"
            activationkey: "{{ rhsm_activation_key | default(omit) }}"
            org_id: "{{ rhsm_org_id | default(omit) }}"
            pool_ids: "{{ rhsm_pool_ids | default(omit) }}"
            state: "{{ rhsm_state | default(omit) }}"
            autosubscribe: "{{ rhsm_autosubscribe | default(omit) }}"
            consumer_name: "{{ rhsm_consumer_hostname | default(omit) }}"
            force_register: True
            rhsm_baseurl: "{{ rhsm_baseurl | default(omit) }}"
          register: subscrition_result
          tags:
            - rhsm
            - rhsm_register

      rescue:
        - name: Clean all local subscription data
          command: subscription-manager clean

        - import_tasks: register.yml

- name: Configure repository subscriptions
  # TODO(jfrancoa): Change back into rhsm_repository once
  # we start using Ansible 2.8.
  rhsm_repository_conf:
    name: "{{ rhsm_repos }}"
    purge: "{{ rhsm_repos_purge | default(omit) }}"
    state: "{{ rhsm_repos_state | default(omit) }}"
  when:
    - rhsm_repos | length > 0
    - rhsm_state == 'present'
    - rhsm_activation_key is not defined or rhsm_method == 'portal'
  tags:
    - rhsm
    - rhsm_repos
