- name: Manage Red Hat subscription
  redhat_subscription:
    username: "{{ rhsm_username | default(omit) }}"
    password: "{{ rhsm_password | default(omit) }}"
    activationkey: "{{ rhsm_activation_key | default(omit) }}"
    org_id: "{{ rhsm_org_id | default(omit) }}"
    pool_ids: "{{ rhsm_pool_ids | default(omit) }}"
    state: "{{ rhsm_state | default(omit) }}"
    autosubscribe: "{{ rhsm_autosubscribe | default(omit) }}"
    consumer_name: "{{ rhsm_consumer_hostname | default(omit) }}"
    force_register: "{{ rhsm_force_register | default(omit) }}"
    rhsm_baseurl: "{{ rhsm_baseurl | default(omit) }}"
  register: subscrition_result
  tags:
    - rhsm
    - rhsm_register
  # Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1715958
  # A regression in Satellite added a delay to the registration to happen.
  # To counter this problem we retry 5 times with a delay of 10 seconds between
  # retries.
  retries: 5
  delay: 10
  until: not subscrition_result.failed
