- name: SATELLITE | Check for Satellite 5
  uri:
    url: "{{ rhsm_satellite_url }}/rhn/Login.do"
    validate_certs: no
    status_code: 200, 404
  register: _sat5_check
  run_once: yes
  tags:
    - rhsm_satellite

- name: SATELLITE | Check for Satellite 6
  uri:
    url: "{{ rhsm_satellite_url }}/katello/api/ping"
    validate_certs: no
    status_code: 200, 404
  register: _sat6_check
  run_once: yes
  tags:
    - rhsm_satellite

- name: SATELLITE | Gather service facts
  service_facts:

- name: SATELLITE | Set list of services as a fact
  set_fact:
    service_list: "{{ services.keys() | list | replace('.service', '') }}"

- name: SATELLITE | Gather package facts
  package_facts:

- name: SATELLITE | Start and enable rhsmcertsd
  service:
    name: rhsmcertd
    state: started
    enabled: yes
  when: "'rhsmcertd' in service_list"

- name: SATELLITE | Set Satellite version
  set_fact:
    rhsm_satellite_version: "{% if _sat5_check['status'] == 200 %}5{% elif _sat6_check['status'] == 200 %}6{% endif %}"
  tags:
    - rhsm_satellite

- name: SATELLITE | Run Satellite {{ rhsm_satellite_version }} tasks
  include_tasks: satellite-{{ rhsm_satellite_version }}.yml
  when: rhsm_state == 'present'
  tags:
    - rhsm_satellite

- import_tasks: portal.yml

# https://bugzilla.redhat.com/show_bug.cgi?id=1717093
- name: SATELLITE 6 | Install katello-host-tools
  when: rhsm_satellite_version == '6'
  package:
    name: katello-host-tools
    state: present
